### PR TITLE
Added a new option: appendTimeString

### PR DESCRIPTION
**Pull request by randybruder**
I wanted to be able to say "2 min read" or "5 min read" with a bit of text after the read time. I added a simple option to the jQuery plugin to allow for an option appendTimeString. Pretty straightforward.

This is my first ever pull request, so I have no idea if I've done it right.

### CODE REVIEW

**Comment by michael-lynch** [comment]
Why not just add the static text to your markup?

```html
<div>
    <span class="eta"></span> read
</div>
```

**Comment by randybruder** [comment]
In case the `reading-time` failed to render, nothing is shown. Otherwise it would leave a "read" after each article.

Plus I'm developing on Squarespace, which has it's shortcomings, like a delay on rendering. So I found even when it would run `reading-time` properly, the could be a fraction of a second delay, showing "read" then "2 min read."

**Comment by michael-lynch** [comment]
I've added some callback functions to handle success and failure.

If the plugin fails, use the new `error` callback. You can remove or manipulate the element how you like from there.

```html
<article>
    <span class="eta"></span> read
</article>
```

```js
$('article').readingTime({
    error: function() {
        $(this).find('.eta').remove();
    }
});
```

The plugin itself is very lightweight at only 4KB, so if there is a delay, it's likely due to <em>how many</em> scripts are being loaded or <em>how</em> the scripts are being loaded.

**Comment by randybruder** [comment]
That works well too, thanks. I concede that any delay is definitely not from your script, but from the Squarespace platform (and I'm pretty sure it's only when an admin is logged in, because it's loading the Squarespace backend as well. So many scripts. All being combined and minified on the fly.)

**Pull request closed without merging**
